import PageHead from "@/components/layout/common/PageHead";
import PageWrapper from "@/components/layout/common/PageWrapper";
import { Alert, Typography } from "@/components/ui";

export const dynamic = "force-dynamic";

export default function AppNotifications() {
  const demoNotifications = [
    {
      id: "1",
      type: "info",
      title: "Welcome to WPGuard",
      message:
        "You’ll receive alerts for plugin updates, security scans, and login activity across connected sites.",
      time: "2025-08-18T09:30:00Z",
      read: true,
    },
    {
      id: "2",
      type: "warning",
      title: "Plugin update available",
      message:
        'Update "SEO Booster" to v4.12 on blog.example.com to patch known vulnerabilities.',
      time: "2025-08-19T14:05:00Z",
      read: false,
    },
    {
      id: "3",
      type: "error",
      title: "Failed login attempts blocked",
      message:
        "5 suspicious login attempts from 203.0.113.25 were blocked in the last hour.",
      time: "2025-08-20T07:22:00Z",
      read: false,
    },
    {
      id: "4",
      type: "success",
      title: "Malware scan clean",
      message:
        "Daily scan completed for shop.example.com. No threats or altered core files detected.",
      time: "2025-08-20T06:00:00Z",
      read: true,
    },
  ];

  return (
    <PageWrapper className="gap-4">
      <PageHead title="Notifications" alignTitle="left" />

      <Alert severity="warning">
        This page is work in progress.
        <strong> Notifications features are not yet implemented.</strong>
      </Alert>

      <p>
        This page shows important alerts generated by WPGuard for your connected
        WordPress sites. Use it to keep track of security events, maintenance
        tasks, and system updates in one place.
        <br />
        New notifications appear at the top. Items may include plugin and theme
        updates, malware scan results, login protections, backup statuses, and
        configuration warnings.
      </p>

      <p>
        Mark items as read in your workflow, or drill into the related site to
        review details and take action. You can customize which alerts you want
        to receive in Settings.
      </p>

      <section className="flex flex-col gap-4 mt-4">
        <Typography variant="h6">Recent notifications (demo)</Typography>
        <ul className="flex flex-col gap-2">
          {demoNotifications.map((n) => (
            <li
              key={n.id}
              className="rounded-md border border-gray-200 p-4 dark:border-gray-800"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <strong className="text-sm">{n.title}</strong>
                    <span
                      className={`inline-flex items-center rounded px-2 py-0.5 text-xs ${
                        n.type === "success"
                          ? "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300"
                          : n.type === "warning"
                          ? "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300"
                          : n.type === "error"
                          ? "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300"
                          : "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300"
                      }`}
                    >
                      {n.type}
                    </span>
                    {!n.read && (
                      <span className="text-xs text-primary-600">New</span>
                    )}
                  </div>
                  <p className="mt-1 text-sm text-gray-700 dark:text-gray-300">
                    {n.message}
                  </p>
                </div>
                <time
                  className="shrink-0 text-xs text-gray-500 dark:text-gray-400"
                  dateTime={n.time}
                  title={new Date(n.time).toLocaleString()}
                >
                  {new Date(n.time).toLocaleString()}
                </time>
              </div>
            </li>
          ))}
        </ul>
      </section>
    </PageWrapper>
  );
}
